"""
Django management command to load all 64 I Ching hexagrams
"""
from django.core.management.base import BaseCommand
from api.models import Hexagram


class Command(BaseCommand):
    help = 'Load all 64 I Ching hexagrams into the database'

    # Complete list of 64 hexagrams in King Wen sequence
    HEXAGRAMS = [
        (1, '111111', '乾', 'Qian', 'The Creative', '111', '111', 'Heaven', 'Heaven',
         ['creation', 'strength', 'pure yang'],
         'The Creative works sublime success, furthering through perseverance.'),
        (2, '000000', '坤', 'Kun', 'The Receptive', '000', '000', 'Earth', 'Earth',
         ['receptivity', 'devotion', 'pure yin'],
         'The Receptive brings sublime success through the perseverance of a mare.'),
        (3, '100010', '屯', 'Zhun', 'Difficulty at the Beginning', '100', '010', 'Thunder', 'Water',
         ['beginning', 'chaos', 'potential'],
         'Difficulty at the beginning works supreme success through persistence.'),
        (4, '010001', '蒙', 'Meng', 'Youthful Folly', '010', '001', 'Water', 'Mountain',
         ['inexperience', 'learning'],
         'Youthful folly brings success by not repeating the first error.'),
        (5, '111010', '需', 'Xu', 'Waiting', '111', '010', 'Heaven', 'Water',
         ['waiting', 'patience', 'nourishment'],
         'Waiting with confidence brings success.'),
        (6, '010111', '訟', 'Song', 'Conflict', '010', '111', 'Water', 'Heaven',
         ['conflict', 'dispute', 'caution'],
         'Conflict requires caution and seeking middle ground.'),
        (7, '010000', '師', 'Shi', 'The Army', '010', '000', 'Water', 'Earth',
         ['discipline', 'leadership'],
         'The army needs discipline and a strong, principled leader.'),
        (8, '000010', '比', 'Bi', 'Holding Together', '000', '010', 'Earth', 'Water',
         ['union', 'alliance'],
         'Holding together brings good fortune.'),
        (9, '111011', '小畜', 'Xiao Xu', 'The Taming Power of the Small', '111', '011', 'Heaven', 'Wind',
         ['accumulation', 'restraint'],
         'Small accumulation: gentle restraint of the strong.'),
        (10, '110111', '履', 'Lu', 'Treading', '110', '111', 'Lake', 'Heaven',
         ['conduct', 'treading', 'care'],
         'Treading on the tail of the tiger: conduct with care.'),
        (11, '111000', '泰', 'Tai', 'Peace', '111', '000', 'Heaven', 'Earth',
         ['peace', 'harmony', 'prosperity'],
         'Peace: heaven and earth unite.'),
        (12, '000111', '否', 'Pi', 'Standstill', '000', '111', 'Earth', 'Heaven',
         ['stagnation', 'obstruction'],
         'Standstill: the great departs, the small approaches.'),
        (13, '101111', '同人', 'Tong Ren', 'Fellowship', '101', '111', 'Fire', 'Heaven',
         ['fellowship', 'community'],
         'Fellowship with others in the open succeeds.'),
        (14, '111101', '大有', 'Da You', 'Possession in Great Measure', '111', '101', 'Heaven', 'Fire',
         ['abundance', 'possession'],
         'Possession in great measure: supreme success.'),
        (15, '001000', '謙', 'Qian2', 'Modesty', '001', '000', 'Mountain', 'Earth',
         ['modesty', 'humility'],
         'Modesty creates success.'),
        (16, '000100', '豫', 'Yu', 'Enthusiasm', '000', '100', 'Earth', 'Thunder',
         ['enthusiasm', 'joy'],
         'Enthusiasm furthers preparation.'),
        (17, '100110', '隨', 'Sui', 'Following', '100', '110', 'Thunder', 'Lake',
         ['following', 'adaptation'],
         'Following brings perseverance and success.'),
        (18, '011001', '蠱', 'Gu', 'Work on the Decayed', '011', '001', 'Wind', 'Mountain',
         ['decay', 'repair'],
         'Work on what has been spoiled.'),
        (19, '110000', '臨', 'Lin', 'Approach', '110', '000', 'Lake', 'Earth',
         ['approach', 'growth'],
         'Approach has supreme success.'),
        (20, '000011', '觀', 'Guan', 'Contemplation', '000', '011', 'Earth', 'Wind',
         ['observation', 'insight'],
         'Contemplation: wash clean until insight arrives.'),
        (21, '100101', '噬嗑', 'Shi He', 'Biting Through', '100', '101', 'Thunder', 'Fire',
         ['decision', 'obstacles'],
         'Biting through brings success.'),
        (22, '101001', '賁', 'Bi2', 'Grace', '101', '001', 'Fire', 'Mountain',
         ['grace', 'beauty', 'form'],
         'Grace: fire at the foot of the mountain.'),
        (23, '000001', '剝', 'Bo', 'Splitting Apart', '000', '001', 'Earth', 'Mountain',
         ['collapse', 'decline'],
         'Splitting apart: unfavorable to go anywhere.'),
        (24, '100000', '復', 'Fu', 'Return', '100', '000', 'Thunder', 'Earth',
         ['return', 'renewal'],
         'Return: success in seven days.'),
        (25, '100111', '無妄', 'Wu Wang', 'Innocence', '100', '111', 'Thunder', 'Heaven',
         ['innocence', 'naturalness'],
         'Innocence: utmost success.'),
        (26, '111001', '大畜', 'Da Xu', 'The Taming Power of the Great', '111', '001', 'Heaven', 'Mountain',
         ['accumulation', 'strength'],
         'Great accumulation: perseverance furthers.'),
        (27, '100001', '頤', 'Yi', 'Nourishment', '100', '001', 'Thunder', 'Mountain',
         ['nourishment', 'self-care'],
         'Nourishment: watch words and food.'),
        (28, '011110', '大過', 'Da Guo', 'Preponderance of the Great', '011', '110', 'Wind', 'Lake',
         ['excess', 'overload'],
         'The great exceeds: the ridgepole sags.'),
        (29, '010010', '坎', 'Kan', 'The Abysmal Water', '010', '010', 'Water', 'Water',
         ['danger', 'depth', 'repetition'],
         'The Abysmal repeated: keep heart steady.'),
        (30, '101101', '離', 'Li', 'The Clinging Fire', '101', '101', 'Fire', 'Fire',
         ['light', 'clarity', 'attachment'],
         'The Clinging repeated: light furthers perseverance.'),
        (31, '001110', '咸', 'Xian', 'Influence', '001', '110', 'Mountain', 'Lake',
         ['influence', 'resonance'],
         'Influence: mutual attraction brings success.'),
        (32, '011100', '恆', 'Heng', 'Duration', '011', '100', 'Wind', 'Thunder',
         ['duration', 'perseverance'],
         'Duration: success through constancy.'),
        (33, '001111', '遯', 'Dun', 'Retreat', '001', '111', 'Mountain', 'Heaven',
         ['retreat', 'withdrawal'],
         'Retreat at the right moment.'),
        (34, '111100', '大壯', 'Da Zhuang', 'The Power of the Great', '111', '100', 'Heaven', 'Thunder',
         ['power', 'strength'],
         'Great power: perseverance furthers.'),
        (35, '000101', '晉', 'Jin', 'Progress', '000', '101', 'Earth', 'Fire',
         ['progress', 'advance'],
         'Progress: the prince is honored.'),
        (36, '101000', '明夷', 'Ming Yi', 'Darkening of the Light', '101', '000', 'Fire', 'Earth',
         ['adversity', 'concealment'],
         'Darkening of the light: keep inner brilliance hidden.'),
        (37, '101011', '家人', 'Jia Ren', 'The Family', '101', '011', 'Fire', 'Wind',
         ['family', 'household'],
         "The family: the woman's perseverance."),
        (38, '110101', '睽', 'Kui', 'Opposition', '110', '101', 'Lake', 'Fire',
         ['opposition', 'divergence'],
         'Opposition: small matters still succeed.'),
        (39, '001010', '蹇', 'Jian', 'Obstruction', '001', '010', 'Mountain', 'Water',
         ['obstruction', 'difficulty'],
         'Obstruction: turn within, unite with friends.'),
        (40, '010100', '解', 'Xie', 'Deliverance', '010', '100', 'Water', 'Thunder',
         ['release', 'deliverance'],
         'Deliverance: the thunder-rain comes.'),
        (41, '110001', '損', 'Sun', 'Decrease', '110', '001', 'Lake', 'Mountain',
         ['decrease', 'sacrifice'],
         'Decrease with sincerity brings great fortune.'),
        (42, '100011', '益', 'Yi2', 'Increase', '100', '011', 'Thunder', 'Wind',
         ['increase', 'benefit'],
         'Increase: favorable to cross the great water.'),
        (43, '111110', '夬', 'Guai', 'Breakthrough', '111', '110', 'Heaven', 'Lake',
         ['breakthrough', 'resolution'],
         'Breakthrough: proclaim truth resolutely.'),
        (44, '011111', '姤', 'Gou', 'Coming to Meet', '011', '111', 'Wind', 'Heaven',
         ['encounter', 'influence'],
         'Coming to meet: the gentle meets the firm.'),
        (45, '000110', '萃', 'Cui', 'Gathering Together', '000', '110', 'Earth', 'Lake',
         ['gathering', 'assembly'],
         'Gathering together brings success.'),
        (46, '011000', '升', 'Sheng', 'Pushing Upward', '011', '000', 'Wind', 'Earth',
         ['ascent', 'growth'],
         'Pushing upward: meet the great man.'),
        (47, '010110', '困', 'Kun2', 'Oppression', '010', '110', 'Water', 'Lake',
         ['oppression', 'exhaustion'],
         'Oppression: perseverance of the great man.'),
        (48, '011010', '井', 'Jing', 'The Well', '011', '010', 'Wind', 'Water',
         ['wellspring', 'renewal'],
         'The well: the town may move, the well cannot.'),
        (49, '101110', '革', 'Ge', 'Revolution', '101', '110', 'Fire', 'Lake',
         ['revolution', 'change'],
         'Revolution on its own day brings trust.'),
        (50, '011101', '鼎', 'Ding', 'The Cauldron', '011', '101', 'Wind', 'Fire',
         ['transformation', 'nourishment'],
         'The cauldron: supreme good fortune.'),
        (51, '100100', '震', 'Zhen', 'The Arousing Thunder', '100', '100', 'Thunder', 'Thunder',
         ['shock', 'arousal'],
         'The Arousing repeated: laughter after fear.'),
        (52, '001001', '艮', 'Gen', 'Keeping Still', '001', '001', 'Mountain', 'Mountain',
         ['stillness', 'meditation'],
         'Keeping still: still the back, forget the body.'),
        (53, '001011', '漸', 'Jian2', 'Development', '001', '011', 'Mountain', 'Wind',
         ['gradual progress', 'marriage'],
         'Gradual development: the maiden marries.'),
        (54, '110100', '歸妹', 'Gui Mei', 'The Marrying Maiden', '110', '100', 'Lake', 'Thunder',
         ['union', 'consequence'],
         'The marrying maiden: misdeeds bring misfortune.'),
        (55, '101100', '豐', 'Feng', 'Abundance', '101', '100', 'Fire', 'Thunder',
         ['abundance', 'climax'],
         'Abundance: act like the midday sun.'),
        (56, '001101', '旅', 'Lu2', 'The Wanderer', '001', '101', 'Mountain', 'Fire',
         ['travel', 'stranger'],
         'The wanderer: perseverance of the small man.'),
        (57, '011011', '巽', 'Xun', 'The Gentle Wind', '011', '011', 'Wind', 'Wind',
         ['gentleness', 'penetration'],
         'The Gentle repeated: success through small steps.'),
        (58, '110110', '兌', 'Dui', 'The Joyous Lake', '110', '110', 'Lake', 'Lake',
         ['joy', 'pleasure'],
         'The Joyous repeated: perseverance brings success.'),
        (59, '010011', '渙', 'Huan', 'Dispersion', '010', '011', 'Water', 'Wind',
         ['dispersion', 'dissolution'],
         'Dispersion: the king approaches the temple.'),
        (60, '110010', '節', 'Jie', 'Limitation', '110', '010', 'Lake', 'Water',
         ['limitation', 'measure'],
         'Limitation: bitter limits should not be persisted in.'),
        (61, '110011', '中孚', 'Zhong Fu', 'Inner Truth', '110', '011', 'Lake', 'Wind',
         ['inner truth', 'sincerity'],
         'Inner truth moves even pigs and fish.'),
        (62, '001100', '小過', 'Xiao Guo', 'Preponderance of the Small', '001', '100', 'Mountain', 'Thunder',
         ['small excess', 'detail'],
         'The small exceeds: the bird should stay low.'),
        (63, '101010', '既濟', 'Ji Ji', 'After Completion', '101', '010', 'Fire', 'Water',
         ['completion', 'caution'],
         'After completion: guard the beginning of decline.'),
        (64, '010101', '未濟', 'Wei Ji', 'Before Completion', '010', '101', 'Water', 'Fire',
         ['incompletion', 'transition'],
         'Before completion: perseverance furthers.'),
    ]

    def handle(self, *args, **options):
        created = 0
        updated = 0

        for hex_data in self.HEXAGRAMS:
            (
                number, binary, chinese, pinyin, english,
                lower_tri, upper_tri, lower_name, upper_name,
                keywords, description
            ) = hex_data

            hexagram, created_flag = Hexagram.objects.update_or_create(
                number=number,
                defaults={
                    'binary': binary,
                    'name_chinese': chinese,
                    'name_pinyin': pinyin,
                    'name_english': english,
                    'line1': binary[0],
                    'line2': binary[1],
                    'line3': binary[2],
                    'line4': binary[3],
                    'line5': binary[4],
                    'line6': binary[5],
                    'lower_trigram': lower_tri,
                    'upper_trigram': upper_tri,
                    'lower_trigram_name': lower_name,
                    'upper_trigram_name': upper_name,
                    'keywords': keywords,
                    'description': description,
                }
            )

            if created_flag:
                created += 1
            else:
                updated += 1

        self.stdout.write(
            self.style.SUCCESS(
                f'Successfully loaded hexagrams: {created} created, {updated} updated'
            )
        )
